# Basic
title: StonesLuo
subtitle: Laziness is the Sin
welcome_message: <a href="https://github.com/StonesLuo/stonesluo.github.io" target="_blank">Blogs Repo</a>
description: CV方向研究生,在读
# creator: <a href="http://onev.cat">@onevcat</a>

url: "https://stonesluo.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
# cover_color:red

# The blog button should not be removed.
blog_button:
    title: 所有博客
    description: Visit blogs

# Navigation buttons in the front page.
nav:
    - {title: CS基础, description: Blogs on ML&DL, url: 'https://stonesluo.github.io/cs-basic/#blog'}
    - {title: 算法, description: Blogs on Algorithm, url: 'https://stonesluo.github.io/algor/#blog'}
    - {title: 机器学习, description: Blogs on ML&DL, url: 'https://stonesluo.github.io/ml-dl/#blog'}
    - {title: 阅读, description: Blogs on Readings, url: 'https://stonesluo.github.io/readings/#blog'}


# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# # Comment 
# comment:
#     disqus: stonesluo
#     # duoshuo: 
    
# Social
social:
    weibo: 2240449160
    github: StonesLuo
    twitter: 302555998
    # facebook: lei.luo.547
    gplus: 107108267983477358170
    mail: 302555998@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
